name: Go Tracer Release
on:
  push:
    branches:
      - release
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  job_one:
    name: Job One
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello!"
      # - uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 0
