version: '3'

services:

  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./example/gorm-postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3.7.8-alpine
    ports:
      - 5671:5671
      - 5672:5672

  couchbase:
    image: couchbase/server:7.1.4
    hostname: couchbase
    ports:
      - '8091-8096:8091-8096'
      - '11210:11210'
    
  couchbase-setup:
    image: amd64/centos:7
    platform: linux/amd64
    depends_on:
      - couchbase
    restart: "no"
    entrypoint:
      - "bash"
      - "-ecx"
      - |
          sleep 30 && \
          curl -v -X POST http://couchbase:8091/pools/default -d memoryQuota=2048 -d indexMemoryQuota=1024 && \
          curl -v http://couchbase:8091/node/controller/setupServices -d services=kv%2Ceventing%2Cindex%2Cn1ql%2Ccbas%2Cfts && \
          curl -v http://couchbase:8091/settings/web -d port=8091 -d username=Administrator -d password=password && \
          curl -i -u Administrator:password -X POST http://couchbase:8091/settings/indexes -d 'storageMode=memory_optimized'

  redis:
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--requirepass", "redispw"]

  mysql:
    image: mysql:8.0.1
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: gopw
      MYSQL_DATABASE: godb
      MYSQL_USER: go
      MYSQL_PASSWORD: gopw
      MYSQL_ROOT_HOST: 0.0.0.0
