version: '3'

services:

  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./example/gorm-postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3.7.8-alpine
    ports:
      - 5671:5671
      - 5672:5672

  couchbase-server-sandbox:
    image: couchbase/server-sandbox:7.1.1
    ports:
      - 8091-8094:8091-8094
      - 11210:11210

  redis:
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--requirepass", "redispw"]

  mysql:
    image: mysql:8.0.1
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: gopw
      MYSQL_DATABASE: godb
      MYSQL_USER: go
      MYSQL_PASSWORD: gopw
      MYSQL_ROOT_HOST: 0.0.0.0
