services:
  couchbase:
    image: public.ecr.aws/docker/library/couchbase:7.6.5
    hostname: couchbase
    ports:
      - "8091-8096:8091-8096"
      - "11210:11210"

  couchbase-setup:
    image: public.ecr.aws/docker/library/alpine:3.21.2
    depends_on:
      - couchbase
    restart: "no"

    entrypoint:
      - "sh"
      - "-ec"
      - |
          apk --no-cache add curl

          echo "Waiting for Couchbase management API..."

          until curl -fsS http://couchbase:8091/pools >/dev/null; do
            echo "Couchbase is not ready yet..."
            sleep 3
          done

          echo "Couchbase management API is ready"

          echo "Configuring memory quotas..."
          curl -fsS -X POST \
            http://couchbase:8091/pools/default \
            -d memoryQuota=2024 \
            -d indexMemoryQuota=512

          echo "Enabling Couchbase services..."
          curl -fsS -X POST \
            http://couchbase:8091/node/controller/setupServices \
            -d services=kv%2Ceventing%2Cindex%2Cn1ql%2Ccbas%2Cfts

          echo "Creating administrator..."
          curl -fsS -X POST \
            http://couchbase:8091/settings/web \
            -d port=8091 \
            -d username=Administrator \
            -d password=password

          echo "Configuring indexes..."
          curl -fsS \
            -u Administrator:password \
            -X POST \
            http://couchbase:8091/settings/indexes \
            -d 'storageMode=memory_optimized'

          echo "Couchbase setup completed successfully"

  postgres:
    image: public.ecr.aws/docker/library/postgres:14

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: mysecretpassword

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d postgres"
        ]
      interval: 5s
      timeout: 5s
      retries: 30
