# (c) Copyright IBM Corp. 2024

---
apiVersion: v1
kind: Secret
metadata:
  name: slack-channel-id
  namespace: currency-monitoring-pipelines
type: Opaque
stringData:
  channelId: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: slack-token
  namespace: currency-monitoring-pipelines
type: Opaque
stringData:
  token: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: currency-monitoring-pipelines
type: Opaque
stringData:
  token: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: github-username
  namespace: currency-monitoring-pipelines
type: Opaque
stringData:
  username: ""


