# (c) Copyright IBM Corp. 2024

---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: run-package-updates-check-task-run-
  namespace: currency-monitoring-pipelines
spec:
  taskRef:
    name: go-tracer-clone-task
  workspaces:
    - name: script-workspace
      emptyDir: { }
