apiVersion: v1
kind: Secret
metadata:
  name: cosmos-conn-url
type: Opaque
stringData:
  # Add url here
  connUrl: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: cosmos-conn-key
type: Opaque
stringData:
  # Add key here
  connKey: ""