apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: go-tracer-ci-pipeline
spec:
  params:
  - name: revision
    type: string
  # - name: cosmosConnURL
  #   type: string
  # - name: cosmosKey
  #   type: string
  workspaces:
    - name: go-tracer-ci-pipeline-pvc
  tasks:
    - name: clone
      params:
      - name: revision
        value: $(params.revision)
      taskRef:
        name: go-tracer-clone-task
      workspaces:
        - name: task-pvc
          workspace: go-tracer-ci-pipeline-pvc

    - name: gofmt
      runAfter:
        - clone
      matrix:
        params:
          - name: imageTag
            value:
              - "1.19"
      taskRef:
        name: go-tracer-gofmt-task
      workspaces:
        - name: task-pvc
          workspace: go-tracer-ci-pipeline-pvc

    - name: goimports
      runAfter:
        - gofmt
      matrix:
        params:
          - name: imageTag
            value:
              - "1.19"
      taskRef:
        name: go-tracer-goimports-task
      workspaces:
        - name: task-pvc
          workspace: go-tracer-ci-pipeline-pvc
    
    - name: unittest
      runAfter:
        - goimports
      matrix:
        params:
          - name: imageTag
            value:
              - "1.19"
      taskRef:
        name: go-tracer-unittest-task
      workspaces:
        - name: task-pvc
          workspace: go-tracer-ci-pipeline-pvc

    - name: integrationtest
      runAfter:
        - unittest
      # params:
      # - name: cosmosConnURL
      #   value: $(params.cosmosConnURL)
      # - name: cosmosKey
      #   value: $(params.cosmosKey)
      matrix:
        params:
          - name: imageTag
            value:
              - "1.19"

      taskRef:
        name: go-tracer-integration-task
      workspaces:
        - name: task-pvc
          workspace: go-tracer-ci-pipeline-pvc
