apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: go-tracer-ci-pipeline
spec:
  params:
  - name: revision
    type: string
  - name: git-commit-sha
    type: string
  - name: go-version
    type: string
  # - name: cosmosConnURL
  #   type: string
  # - name: cosmosKey
  #   type: string
  workspaces:
    - name: go-tracer-ci-pipeline-pvc
  tasks:

    - name: github-set-check-status-to-pending
      taskRef:
        kind: Task
        name: github-set-status
      params:
      - name: SHA
        value: $(params.git-commit-sha)
      - name: STATE
        value: pending
      - name: PIPELINE_RUN_NAME
        value: $(context.pipelineRun.name)
      - name: go-version
        value: $(params.go-version)

    - name: clone
      params:
      - name: revision
        value: $(params.revision)
      taskRef:
        name: go-tracer-clone-task
      workspaces:
        - name: task-pvc
          workspace: go-tracer-ci-pipeline-pvc

    - name: gofmt
      runAfter:
        - clone
      params:
      - name: imageTag
        value: $(params.go-version)
      - name: excludeDirs
        value: ""
      # matrix:
      #   include:
      #     - name: build-117
      #       params:
      #         - name: imageTag
      #           value: "1.17"
      #         - name: excludeDirs
      #           value: "./internal/bin/sql ./example/gin ./example/sql-redis ./example/gorm-postgres ./example/gorm-sqlite ./example/grpc-client-server ./instrumentation/cloud.google.com/go ./instrumentation/instabeego ./example/beego ./instrumentation/instaawsv2 ./instrumentation/instaecho ./instrumentation/instagorm ./instrumentation/instaamqp ./instrumentation/instaawssdk ./instrumentation/instagocb ./example/couchbase ./instrumentation/instacosmos ./example/cosmos ./instrumentation/instamongo"
      #     - name: build-118
      #       params:
      #         - name: imageTag
      #           value: "1.18"
      #         - name: excludeDirs
      #           value: "./example/grpc-client-server ./instrumentation/cloud.google.com/go ./instrumentation/instaawsv2 ./instrumentation/instaamqp ./instrumentation/instaawssdk ./instrumentation/instagocb ./example/couchbase"
      #     - name: build-119
      #       params:
      #         - name: imageTag
      #           value: "1.19"
      #         - name: excludeDirs
      #           value: ""
      #     - name: build-120
      #       params:
      #         - name: imageTag
      #           value: "1.20"
      #         - name: excludeDirs
      #           value: ""
      #     - name: build-121
      #       params:
      #         - name: imageTag
      #           value: "1.21"
      #         - name: excludeDirs
      #           value: ""
      taskRef:
        name: go-tracer-gofmt-task
      workspaces:
        - name: task-pvc
          workspace: go-tracer-ci-pipeline-pvc

    - name: goimports
      runAfter:
        - gofmt
      params:
      - name: imageTag
        value: $(params.go-version)
      - name: excludeDirs
        value: ""
      # matrix:
      #   include:
      #     - name: build-117
      #       params:
      #         - name: imageTag
      #           value: "1.17"
      #         - name: excludeDirs
      #           value: ".//internal/bin/sql ./example/gin ./example/sql-redis ./example/gorm-postgres ./example/gorm-sqlite ./example/grpc-client-server ./instrumentation/cloud.google.com/go ./instrumentation/instabeego ./example/beego ./instrumentation/instaawsv2 ./instrumentation/instaecho ./instrumentation/instagorm ./instrumentation/instaamqp ./instrumentation/instaawssdk ./instrumentation/instagocb ./example/couchbase ./instrumentation/instacosmos ./example/cosmos ./instrumentation/instamongo"
      #     - name: build-118
      #       params:
      #         - name: imageTag
      #           value: "1.18"
      #         - name: excludeDirs
      #           value: "./example/grpc-client-server ./instrumentation/cloud.google.com/go ./instrumentation/instaawsv2 ./instrumentation/instaamqp ./instrumentation/instaawssdk ./instrumentation/instagocb ./example/couchbase"
      #     - name: build-119
      #       params:
      #         - name: imageTag
      #           value: "1.19"
      #         - name: excludeDirs
      #           value: ""
      #     - name: build-120
      #       params:
      #         - name: imageTag
      #           value: "1.20"
      #         - name: excludeDirs
      #           value: ""
      #     - name: build-121
      #       params:
      #         - name: imageTag
      #           value: "1.21"
      #         - name: excludeDirs
      #           value: ""
      taskRef:
        name: go-tracer-goimports-task
      workspaces:
        - name: task-pvc
          workspace: go-tracer-ci-pipeline-pvc
    
    - name: unittest
      runAfter:
        - goimports
      params:
      - name: imageTag
        value: $(params.go-version)
      - name: excludeDirs
        value: ""
      # matrix:
      #   include:
      #     - name: build-117
      #       params:
      #         - name: imageTag
      #           value: "1.17"
      #         - name: excludeDirs
      #           value: "./internal/bin/sql ./example/gin ./example/sql-redis ./example/gorm-postgres ./example/gorm-sqlite ./example/grpc-client-server ./instrumentation/cloud.google.com/go ./instrumentation/instabeego ./example/beego ./instrumentation/instaawsv2 ./instrumentation/instaecho ./instrumentation/instagorm ./instrumentation/instaamqp ./instrumentation/instaawssdk ./instrumentation/instagocb ./example/couchbase ./instrumentation/instacosmos ./example/cosmos ./instrumentation/instamongo"
      #     - name: build-118
      #       params:
      #         - name: imageTag
      #           value: "1.18"
      #         - name: excludeDirs
      #           value: "./example/grpc-client-server ./instrumentation/cloud.google.com/go ./instrumentation/instaawsv2 ./instrumentation/instaamqp ./instrumentation/instaawssdk ./instrumentation/instagocb ./example/couchbase"
      #     - name: build-119
      #       params:
      #         - name: imageTag
      #           value: "1.19"
      #         - name: excludeDirs
      #           value: ""
      #     - name: build-120
      #       params:
      #         - name: imageTag
      #           value: "1.20"
      #         - name: excludeDirs
      #           value: ""
      #     - name: build-121
      #       params:
      #         - name: imageTag
      #           value: "1.21"
      #         - name: excludeDirs
      #           value: ""
      taskRef:
        name: go-tracer-unittest-task
      workspaces:
        - name: task-pvc
          workspace: go-tracer-ci-pipeline-pvc

    - name: integrationtestcommon
      runAfter:
        - unittest
      params:
      - name: imageTag
        value: $(params.go-version)
      - name: excludeDirs
        value: ""
      # matrix:
      #   include:
      #     - name: build-117
      #       params:
      #         - name: imageTag
      #           value: "1.17"
      #         - name: excludeDirs
      #           value: "./internal/bin/sql ./example/gin ./example/sql-redis ./example/gorm-postgres ./example/gorm-sqlite ./example/grpc-client-server ./instrumentation/cloud.google.com/go ./instrumentation/instabeego ./example/beego ./instrumentation/instaawsv2 ./instrumentation/instaecho ./instrumentation/instagorm ./instrumentation/instaamqp ./instrumentation/instaawssdk ./instrumentation/instagocb ./example/couchbase ./instrumentation/instacosmos ./example/cosmos ./instrumentation/instamongo"
      #     - name: build-118
      #       params:
      #         - name: imageTag
      #           value: "1.18"
      #         - name: excludeDirs
      #           value: "./example/grpc-client-server ./instrumentation/cloud.google.com/go ./instrumentation/instaawsv2 ./instrumentation/instaamqp ./instrumentation/instaawssdk ./instrumentation/instagocb ./example/couchbase"
      #     - name: build-119
      #       params:
      #         - name: imageTag
      #           value: "1.19"
      #         - name: excludeDirs
      #           value: ""
      #     - name: build-120
      #       params:
      #         - name: imageTag
      #           value: "1.20"
      #         - name: excludeDirs
      #           value: ""
      #     - name: build-121
      #       params:
      #         - name: imageTag
      #           value: "1.21"
      #         - name: excludeDirs
      #           value: ""

      taskRef:
        name: go-tracer-integration-task
      workspaces:
        - name: task-pvc
          workspace: go-tracer-ci-pipeline-pvc

    - name: integrationtestcouchbase
      runAfter:
        - integrationtestcommon
      params:
      - name: imageTag
        value: $(params.go-version)
      - name: excludeDirs
        value: ""
      # matrix:
      #   params:
      #     - name: imageTag
      #       value:
      #         - "1.19"

      taskRef:
        name: go-tracer-integration-couchbase-task
      workspaces:
        - name: task-pvc
          workspace: go-tracer-ci-pipeline-pvc

  finally:
    - name: github-set-check-status-to-success-or-failure
      taskRef:
        kind: Task
        name: github-set-status
      params:
      - name: SHA
        value: $(params.git-commit-sha)
      - name: STATE
        value: "$(tasks.status)"
      - name: PIPELINE_RUN_NAME
        value: $(context.pipelineRun.name)
      - name: go-version
        value: $(params.go-version)