# (c) Copyright IBM Corp. 2024

apiVersion: v1
kind: Secret
metadata:
  name: cosmos-conn-url
type: Opaque
stringData:
  # Add url here
  connUrl: "<<COSMOS_URL>>"
---
apiVersion: v1
kind: Secret
metadata:
  name: cosmos-conn-key
type: Opaque
stringData:
  # Add key here
  connKey: "<<COSMOS_KEY>>"
---
apiVersion: v1
kind: Secret
metadata:
  name: github-interceptor-secret
type: Opaque
stringData:
  # Always use a long, strong and random generated token
  secretToken: "<<WEBHOOK_SECRET>>"

---
apiVersion: v1
kind: Secret
metadata:
  name: github-token
type: Opaque
stringData:
  token: "<<GITHUB_BOT_TOKEN>>"
