---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: go-tracer-clone-task
spec:
  params:
    - name: revision
      type: string
  workspaces:
    - name: task-pvc
      mountPath: /workspace
  steps:
    - name: clone
      image: alpine/git
      script: |
        #!/bin/sh
        echo "Cloning repo!"
        cd /workspace && git clone --depth 1 -b tests-fix https://github.com/instana/go-sensor
        ls -lah /workspace

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: go-tracer-unittest-task
spec:
  params:
    - name: imageTag
      type: string
  workspaces:
    - name: task-pvc
      mountPath: /workspace
  steps:
    - name: unittest
      image: golang:$(params.imageTag)
      env:
        - name: RUN_LINTER
          # need to change this before merge
          value: "no"
        - name: GO111MODULE
          value: "auto"
        - name: VENDOR_DEPS
          value: "no"
      workingDir: /workspace/go-sensor/
      script: |
        #!/bin/sh
        echo "Running unit tests!"
        make test

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: go-tracer-gofmt-task
spec:
  params:
    - name: imageTag
      type: string
  workspaces:
    - name: task-pvc
      mountPath: /workspace
  steps:
    - name: gofmt
      image: golang:$(params.imageTag)
      workingDir: /workspace/go-sensor/
      script: |
        #!/bin/sh
        echo "Running go fmt check!"
        make fmtcheck

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: go-tracer-goimports-task
spec:
  params:
    - name: imageTag
      type: string
  workspaces:
    - name: task-pvc
      mountPath: /workspace
  steps:
    - name: goimports
      image: golang:$(params.imageTag)
      workingDir: /workspace/go-sensor/
      script: |
        #!/bin/sh
        echo "Installing go imports!"
        go install golang.org/x/tools/cmd/goimports@latest || true
        echo "Running import check"
        make importcheck
        

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: go-tracer-integration-task
spec:
  sidecars:
    - name: couchbase
      image: couchbase/server-sandbox:7.2.4
      readinessProbe:
        httpGet:
           path: /ui/index.html
           port: 8091
        initialDelaySeconds: 60
    - name: postgresql
      image: postgres:14
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "mysecretpassword"
  params:
  - name: imageTag
    type: string
  # - name: cosmosConnURL
  #   type: string
  # - name: cosmosKey
  #   type: string
  workspaces:
    - name: task-pvc
      mountPath: /workspace
  steps:
    - name: integrationtest
      image: golang:$(params.imageTag)
      env:
        - name: GO111MODULE
          value: "auto"
        - name: VENDOR_DEPS
          value: "no"
        - name: COSMOS_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: "cosmos-conn-url"
              key: "connUrl"
        - name: COSMOS_KEY
          valueFrom:
            secretKeyRef:
              name: "cosmos-conn-key"
              key: "connKey"
        - name: EXCLUDE_DIRS
          value: ""
      workingDir: /workspace/go-sensor/
      script: |
        #!/bin/sh
        echo "Running integration tests!"
        make integration
