name: Go Tracer Release

on:
  workflow_dispatch:
    secrets:
      GH_TOKEN_TRACER_RELEASE:
        description: 'Token with permissions to release the Go Tracer and its instrumentations'
    inputs:
      packageName:
        description: 'Example: instagorm, instaredis/v2. Use "." to release the core module'
        required: true
        default: '.'
        type: string
      versionType:
        description: 'The version to be released: major, minor or patch'
        required: true
        default: 'patch'
        type: choice
        options:
        - major
        - minor
        - patch
      asDraft:
        description: 'Release as draft?'
        required: true
        default: true
        type: boolean

jobs:
  do_release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout repo
      with:
        fetch-depth: 0
    # Theoretically we don't need to run tests if the action will run in the main branch, which is supposed to be always green
    # - name: Tests
    #   run: make test
    - name: Release tracer or package
      run: ./release_action.sh
      shell: bash {0}
      env:
        INSTANA_PACKAGE_NAME: ${{ inputs.packageName }}
        LIB_VERSION_TYPE: ${{ inputs.versionType }}
        RELEASE_AS_DRAFT: ${{ inputs.asDraft }}
        GH_TOKEN_TRACER_RELEASE: ${{ secrets.GH_TOKEN_TRACER_RELEASE }}
