# This workflow creates a pull request updating all instrumented packages to point to the latest core module.
# If the PR has errors, manually fix whatever errors poped up and merge it to master.
# Then, run the "Update all instrumentations RELEASE" action to release them all.

name: Update all instrumentations PR

on:
  workflow_dispatch:

jobs:
  updade_instrumentations:
    name: Update instrumentations
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout repo
      with:
        fetch-depth: 0
    - name: Creating branch
      id: create-branch
      run: |
        CORE_TAG=$(git tag -l "v1.*" | sort -V | tail -n1)

        echo "CORE_TAG=$CORE_TAG" >> $GITHUB_OUTPUT
        echo "New core version is $CORE_TAG"

        #!/bin/bash

        EXCLUDED_DIRS="\/.*\/example"

        # List of instrumentation folders
        LIB_LIST=$(find ./instrumentation -name go.mod -exec dirname {} \; | grep -E -v "$EXCLUDED_DIRS")

        git config user.name "IBM/Instana/Team Go"
        git config user.email "github-actions@github.com"
        git checkout update-instrumentations-core-"$CORE_TAG" || git checkout -b update-instrumentations-core-"$CORE_TAG"

        git pull origin "update-instrumentations-core-$CORE_TAG" || echo "Brand new branch. No need to pull from origin."

        # Updates all instrumentations to use the @latest version of the core module
        for lib in $LIB_LIST
          do cd "$lib" && go mod edit -droprequire github.com/instana/go-sensor && go get github.com/instana/go-sensor@$CORE_TAG && go mod tidy && cd -;
        done

        git add .
        git commit -m "Updating instrumentations to core module $CORE_TAG"

    - name: Push branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ github.token }}
        branch: update-instrumentations-core-${{ steps.create-branch.outputs.CORE_TAG }}

    - name: Create PR
      run: |
        CORE_TAG=${{ steps.create-branch.outputs.CORE_TAG }}
        git checkout update-instrumentations-core-"$CORE_TAG"
        gh pr create --title "Updating instrumentations to core module $CORE_TAG" --body "This PR updates all instrumented packages to use the latest core module $CORE_TAG." --head $(git branch --show-current)
      env:
        GH_TOKEN: ${{ github.token }}
